# Generated by Django 5.2 on 2025-09-19 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('template_type', models.CharField(choices=[('new_lead', 'Нова заявка'), ('lead_confirmation', 'Підтвердження заявки'), ('quote_sent', 'Пропозиція відправлена'), ('follow_up', 'Нагадування')], max_length=20, verbose_name='Тип шаблону')),
                ('subject_uk', models.CharField(max_length=200, verbose_name='Тема (УК)')),
                ('subject_ru', models.CharField(max_length=200, verbose_name='Тема (РУ)')),
                ('subject_en', models.CharField(max_length=200, verbose_name='Тема (EN)')),
                ('content_uk', models.TextField(verbose_name='Контент (УК)')),
                ('content_ru', models.TextField(verbose_name='Контент (РУ)')),
                ('content_en', models.TextField(verbose_name='Контент (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Email шаблон',
                'verbose_name_plural': 'Email шаблони',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефону має бути у форматі: "+380501234567". До 15 цифр.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компанія')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('inquiry_type', models.CharField(choices=[('price_request', 'Запит ціни'), ('tech_consultation', 'Технічна консультація'), ('partnership', 'Партнерство'), ('service', 'Сервіс'), ('other', 'Інше')], default='price_request', max_length=20, verbose_name='Тип запиту')),
                ('product_name', models.CharField(blank=True, help_text='Назва продукту або тип обладнання', max_length=200, verbose_name='Продукт')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('budget_range', models.CharField(blank=True, help_text='Орієнтовний бюджет проекту', max_length=100, verbose_name='Бюджет')),
                ('project_timeline', models.CharField(blank=True, max_length=200, verbose_name='Терміни проекту')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='Сторінка джерела')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Реферер')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('language', models.CharField(default='uk', max_length=10, verbose_name='Мова')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('contacted', "Зв'язалися"), ('quote_sent', 'Відправили пропозицію'), ('closed_won', 'Закрито (продано)'), ('closed_lost', 'Закрито (втрачено)'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('consent_gdpr', models.BooleanField(default=False, verbose_name='Згода на обробку даних')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='Згода на маркетинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата контакту')),
                ('internal_notes', models.TextField(blank=True, help_text='Примітки для команди (не видимі клієнту)', verbose_name='Внутрішні примітки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва джерела')),
                ('utm_source', models.CharField(blank=True, max_length=50, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=50, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Джерело заявки',
                'verbose_name_plural': 'Джерела заявок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email увімкнено')),
                ('email_recipients', models.TextField(default='admin@adiabatic.com', help_text='Email адреси через кому', verbose_name='Email одержувачі')),
                ('email_subject_template', models.CharField(default='Нова заявка від {name}', max_length=200, verbose_name='Шаблон теми email')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram увімкнено')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('viber_enabled', models.BooleanField(default=False, verbose_name='Viber увімкнено')),
                ('viber_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Viber Bot Token')),
                ('viber_admin_id', models.CharField(blank=True, max_length=50, verbose_name='Viber Admin ID')),
                ('notification_delay', models.PositiveIntegerField(default=5, help_text='Затримка перед відправкою', verbose_name='Затримка нотифікації (сек)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Максимум спроб')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування нотифікацій',
                'verbose_name_plural': 'Налаштування нотифікацій',
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Створено'), ('email_sent', 'Email відправлено'), ('telegram_sent', 'Telegram відправлено'), ('viber_sent', 'Viber відправлено'), ('status_changed', 'Статус змінено'), ('contacted', 'Контакт здійснено'), ('note_added', 'Додано примітку')], max_length=20, verbose_name='Тип активності')),
                ('description', models.TextField(verbose_name='Опис')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='Користувач')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Активність заявки',
                'verbose_name_plural': 'Активності заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource', verbose_name='Джерело'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone_709d42_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
