services:
  - type: web
    name: adiabatic-django
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py setup_data
      python manage.py import_real_3d_files --copy-files
    startCommand: gunicorn adiabatic.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: adiabatic-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: adiabatic-django.onrender.com,adiabatic-django-*.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://adiabatic-django.onrender.com,https://adiabatic-django-*.onrender.com
      - key: SITE_URL
        value: https://adiabatic-django.onrender.com
      - key: REDIS_URL
        value: redis://red-xxxxx:6379

databases:
  - name: adiabatic-db
    databaseName: adiabatic
    user: adiabatic_user
    plan: free
