# Generated by Django 5.1.3 on 2025-08-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код мови')),
                ('name', models.CharField(max_length=50, verbose_name='Назва мови')),
                ('name_local', models.CharField(max_length=50, verbose_name='Назва мови місцевою мовою')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('flag', models.ImageField(blank=True, upload_to='flags/', verbose_name='Прапор')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва меню')),
                ('menu_type', models.CharField(choices=[('header', 'Верхнє меню'), ('footer', 'Нижнє меню'), ('mobile', 'Мобільне меню')], max_length=20, verbose_name='Тип меню')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['menu_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adiabatic', max_length=100, verbose_name='Назва сайту')),
                ('site_description', models.TextField(blank=True, verbose_name='Опис сайту')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактний email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактний телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=20, verbose_name='Yandex Metrika ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('is_external', models.BooleanField(default=False, verbose_name='Зовнішнє посилання')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Відкривати в новій вкладці')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu', verbose_name='Меню')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Сторінка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Батьківський елемент')),
            ],
            options={
                'verbose_name': 'Елемент меню',
                'verbose_name_plural': 'Елементи меню',
                'ordering': ['menu', 'order', 'title'],
            },
        ),
    ]
