# Generated by Django 5.2 on 2025-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('monobank_token', models.CharField(blank=True, max_length=200, verbose_name='Monobank Token')),
                ('monobank_webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('iban', models.CharField(blank=True, max_length=29, verbose_name='IBAN')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name="Ім'я отримувача")),
                ('recipient_code', models.CharField(blank=True, max_length=20, verbose_name='Код отримувача')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активні')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування платежів',
                'verbose_name_plural': 'Налаштування платежів',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Перегляд сторінки'), ('form_submit', 'Відправка форми'), ('download', 'Завантаження'), ('contact', 'Контакт'), ('product_view', 'Перегляд продукту')], max_length=20, verbose_name='Тип події')),
                ('event_name', models.CharField(max_length=100, verbose_name='Назва події')),
                ('page_url', models.URLField(max_length=500, verbose_name='URL сторінки')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Подія аналітики',
                'verbose_name_plural': 'Події аналітики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='core_analyt_event_t_b37de5_idx'), models.Index(fields=['created_at'], name='core_analyt_created_45f7e6_idx')],
            },
        ),
    ]
