# Generated by Django 5.1.3 on 2025-08-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рус)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (англ)')),
                ('subtitle_uk', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (укр)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (рус)')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (англ)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (рус)')),
                ('description_en', models.TextField(blank=True, verbose_name='Опис (англ)')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Фонове зображення')),
                ('cta_text_uk', models.CharField(default='Дізнатися більше', max_length=50, verbose_name='Текст кнопки (укр)')),
                ('cta_text_ru', models.CharField(default='Дізнатися більше', max_length=50, verbose_name='Текст кнопки (рус)')),
                ('cta_text_en', models.CharField(default='Дізнатися більше', max_length=50, verbose_name='Текст кнопки (англ)')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='URL кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Hero секція',
                'verbose_name_plural': 'Hero секції',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Головна'), ('about', 'Про компанію'), ('contacts', 'Контакти'), ('products', 'Продукція'), ('custom', 'Кастомна сторінка')], max_length=20, unique=True, verbose_name='Тип сторінки')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рус)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (англ)')),
                ('content_uk', models.TextField(blank=True, verbose_name='Контент (укр)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Контент (рус)')),
                ('content_en', models.TextField(blank=True, verbose_name='Контент (англ)')),
                ('meta_title_uk', models.CharField(blank=True, max_length=60, verbose_name='Meta title (укр)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=60, verbose_name='Meta title (рус)')),
                ('meta_title_en', models.CharField(blank=True, max_length=60, verbose_name='Meta title (англ)')),
                ('meta_description_uk', models.TextField(blank=True, max_length=160, verbose_name='Meta description (укр)')),
                ('meta_description_ru', models.TextField(blank=True, max_length=160, verbose_name='Meta description (рус)')),
                ('meta_description_en', models.TextField(blank=True, max_length=160, verbose_name='Meta description (англ)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('website_url', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero секція'), ('text', 'Текстова секція'), ('image', 'Зображення'), ('gallery', 'Галерея'), ('features', 'Особливості'), ('testimonials', 'Відгуки'), ('cta', 'Call to Action'), ('contact', 'Контактна форма')], max_length=20, verbose_name='Тип секції')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секції')),
                ('content', models.JSONField(default=dict, verbose_name='Контент секції')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Секція',
                'verbose_name_plural': 'Секції',
                'ordering': ['page', 'order'],
            },
        ),
    ]
