# Generated by Django 5.2 on 2025-12-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва (укр)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Назва (рус)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Назва (англ)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_description_uk', models.TextField(max_length=300, verbose_name='Короткий опис (укр)')),
                ('short_description_ru', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (рус)')),
                ('short_description_en', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (англ)')),
                ('full_description_uk', models.TextField(verbose_name='Повний опис (укр)')),
                ('full_description_ru', models.TextField(blank=True, verbose_name='Повний опис (рус)')),
                ('full_description_en', models.TextField(blank=True, verbose_name='Повний опис (англ)')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення 3')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Технічні характеристики')),
                ('advantages_uk', models.TextField(blank=True, verbose_name='Переваги (укр)')),
                ('advantages_ru', models.TextField(blank=True, verbose_name='Переваги (рус)')),
                ('advantages_en', models.TextField(blank=True, verbose_name='Переваги (англ)')),
                ('applications_uk', models.TextField(blank=True, verbose_name='Галузі застосування (укр)')),
                ('applications_ru', models.TextField(blank=True, verbose_name='Галузі застосування (рус)')),
                ('applications_en', models.TextField(blank=True, verbose_name='Галузі застосування (англ)')),
                ('icon_emoji', models.CharField(default='🔧', max_length=10, verbose_name='Іконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('meta_title_uk', models.CharField(blank=True, max_length=60, verbose_name='Meta title (укр)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=60, verbose_name='Meta title (рус)')),
                ('meta_title_en', models.CharField(blank=True, max_length=60, verbose_name='Meta title (англ)')),
                ('meta_description_uk', models.TextField(blank=True, max_length=160, verbose_name='Meta description (укр)')),
                ('meta_description_ru', models.TextField(blank=True, max_length=160, verbose_name='Meta description (рус)')),
                ('meta_description_en', models.TextField(blank=True, max_length=160, verbose_name='Meta description (англ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['order', 'title_uk'],
            },
        ),
    ]
