# Generated by Django 5.2 on 2025-12-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.CharField(blank=True, default='', help_text='Шлях до файлу в static, наприклад: images/tovar1.png', max_length=200, verbose_name='Зображення 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.CharField(blank=True, default='', help_text='Шлях до файлу в static, наприклад: images/tovar11.png', max_length=200, verbose_name='Зображення 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.CharField(blank=True, default='', help_text='Шлях до файлу в static, наприклад: images/tovar111.png', max_length=200, verbose_name='Зображення 3'),
        ),
    ]
