# Generated by Django 5.1.3 on 2025-08-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Назва (УК)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Назва (РУ)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (УК)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (РУ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Опис (EN)')),
                ('icon', models.CharField(blank=True, help_text='CSS клас іконки (наприклад: fas fa-cog)', max_length=50, verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Назва (УК)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Назва (РУ)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('short_description_uk', models.TextField(max_length=300, verbose_name='Короткий опис (УК)')),
                ('short_description_ru', models.TextField(max_length=300, verbose_name='Короткий опис (РУ)')),
                ('short_description_en', models.TextField(max_length=300, verbose_name='Короткий опис (EN)')),
                ('description_uk', models.TextField(verbose_name='Повний опис (УК)')),
                ('description_ru', models.TextField(verbose_name='Повний опис (РУ)')),
                ('description_en', models.TextField(verbose_name='Повний опис (EN)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='products/hero/', verbose_name='Головне зображення')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна (USD)')),
                ('meta_title_uk', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок (УК)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок (РУ)')),
                ('meta_title_en', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок (EN)')),
                ('meta_description_uk', models.CharField(blank=True, max_length=160, verbose_name='Meta опис (УК)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, verbose_name='Meta опис (РУ)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta опис (EN)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['-is_featured', 'category__order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='ProductAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100, verbose_name='Заголовок (УК)')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок (РУ)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок (EN)')),
                ('description_uk', models.TextField(max_length=300, verbose_name='Опис (УК)')),
                ('description_ru', models.TextField(max_length=300, verbose_name='Опис (РУ)')),
                ('description_en', models.TextField(max_length=300, verbose_name='Опис (EN)')),
                ('icon', models.CharField(blank=True, help_text='CSS клас іконки (наприклад: fas fa-check)', max_length=50, verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Перевага продукту',
                'verbose_name_plural': 'Переваги продукту',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва документу (УК)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Назва документу (РУ)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Назва документу (EN)')),
                ('document_type', models.CharField(choices=[('certificate', 'Сертифікат'), ('manual', 'Інструкція'), ('datasheet', 'Технічний лист'), ('warranty', 'Гарантія'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип документу')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публічний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Документ продукту',
                'verbose_name_plural': 'Документи продукту',
                'ordering': ['order', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Зображення галереї',
                'verbose_name_plural': 'Галерея продукту',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Характеристика (УК)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Характеристика (РУ)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Характеристика (EN)')),
                ('value', models.CharField(max_length=200, verbose_name='Значення')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Одиниця виміру')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Технічна характеристика',
                'verbose_name_plural': 'Технічні характеристики',
                'ordering': ['order', 'name_uk'],
            },
        ),
    ]
