# Generated by Django 5.2 on 2025-08-27 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_productdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ['order', 'content_type'], 'verbose_name': 'Елемент галереї', 'verbose_name_plural': 'Галерея продукту'},
        ),
        migrations.AddField(
            model_name='product',
            name='application_type',
            field=models.CharField(blank=True, choices=[('INDUSTRIAL', 'Промислові системи'), ('ENERGY', 'Енергетичне обладнання'), ('COMPACT', 'Компактні рішення'), ('CUSTOM', 'Спеціальні рішення'), ('FOOD', 'Харчова промисловість'), ('OIL_GAS', 'Нафтогазова галузь'), ('HVAC', 'Системи кондиціонування'), ('MARINE', 'Морське обладнання')], max_length=20, verbose_name='Тип застосування'),
        ),
        migrations.AddField(
            model_name='product',
            name='fluid_type',
            field=models.CharField(blank=True, choices=[('WATER', 'Вода'), ('STEAM', 'Пара'), ('OIL', 'Мастило/Нафтопродукти'), ('GAS', 'Газ'), ('AIR', 'Повітря'), ('REFRIGERANT', 'Хладагент'), ('CHEMICAL', 'Хімічні речовини'), ('MIXED', 'Змішані середовища')], max_length=20, verbose_name='Тип теплоносія'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_shell',
            field=models.CharField(blank=True, max_length=100, verbose_name='Матеріал корпусу'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_tubes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Матеріал трубок'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_pressure_bar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Макс. тиск (bar)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Макс. температура (°C)'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Потужність (kW)'),
        ),
        migrations.AddField(
            model_name='product',
            name='standards',
            field=models.CharField(blank=True, help_text='ASME, DIN, GOST тощо', max_length=200, verbose_name='Стандарти'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='content_type',
            field=models.CharField(choices=[('IMAGE', 'Зображення'), ('3D_MODEL', '3D модель'), ('TECHNICAL_DRAWING', 'Технічне креслення'), ('ANIMATION', 'Анімація'), ('VIDEO', 'Відео')], default='IMAGE', max_length=20, verbose_name='Тип контенту'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість завантажень'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='file_3d',
            field=models.FileField(blank=True, help_text='Формати: .stp, .step, .iges, .obj, .gltf, .glb', null=True, upload_to='products/3d/', verbose_name='3D модель/файл'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Розмір файлу'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='is_downloadable',
            field=models.BooleanField(default=True, verbose_name='Доступний для завантаження'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Зображення для превью 3D моделі', null=True, upload_to='products/3d/previews/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (РУ)'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (УК)'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Зображення'),
        ),
    ]
