# Generated by Django 5.2 on 2025-09-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_3d_support_and_tech_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва (УК)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Назва (РУ)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Назва (EN)')),
                ('document_type', models.CharField(choices=[('certificate', 'Сертифікат'), ('datasheet', 'Технічний паспорт'), ('manual', 'Інструкція'), ('warranty', 'Гарантійний талон'), ('drawing', 'Креслення')], default='certificate', max_length=20, verbose_name='Тип документу')),
                ('file', models.FileField(help_text='PDF, DOC, або інші документи', upload_to='products/documents/', verbose_name='Файл документу')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='products/qr_codes/', verbose_name='QR код')),
                ('qr_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID для QR')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публічний доступ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Документ продукту',
                'verbose_name_plural': 'Документи продукту',
                'ordering': ['order', 'document_type'],
            },
        ),
    ]
